### ISSUE TITLE
Please Add a Limits API

### ISSUE THREAD

**Issue by Shinmera** [tootsuite/documentation#636] opened 2018-06-09 08:32 UTC
At the moment the number of characters a status may contain and the number of characters a link is going to be shortened to are not accessible through the API and must instead be hard-coded into the client. If these numbers ever change, all existing clients need to be manually updated to conform to the new limits.

If the API instead exposed a specific endpoint, or encoded this information into an existing one (like `/v1/instance`), then clients could automatically determine the current limits and adjust themselves accordingly.

**Comment by Tagadda** [comment] 2018-06-09 09:14
For now, Mastodon only support 500 chars toots.

Some forks increase this limit, and some (like glitch-soc) implement a `max_toot_chars` attribute in `/v1/instance` as you said.

**Comment by nightpool** [comment] 2018-06-09 17:03
Feature requests for mastodon itself should go on the mastodon repo, not on the documentation.

The request is a duplicate of https://github.com/tootsuite/mastodon/issues/4915

**Closed by nightpool** 2018-06-09 17:03 UTC
